### ISSUE TITLE
Need dependency for apol [ImportError: No module named PyQt5.QtWidgets]

### ISSUE THREAD

**Issue by freedom1b2830** [archlinuxhardened/selinux#111]
```
python2   /etc/selinux/refpolicy-freedom1b2830/policy/policy.33
  File "/etc/selinux/refpolicy-freedom1b2830/policy/policy.33", line 1
SyntaxError: Non-ASCII character '\x8c' in file /etc/selinux/refpolicy-freedom1b2830/policy/policy.33 on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
[root@archlinux freedom1b2830_FORK]# python2 /usr/bin/apol   /etc/selinux/refpolicy-freedom1b2830/policy/policy.33
Traceback (most recent call last):
  File "/usr/bin/apol", line 24, in <module>
    from PyQt5.QtWidgets import QApplication
ImportError: No module named PyQt5.QtWidgets
```

need ``python2-pyqt5``
for
pacman -F apol
```
selinux/setools 4.4.0-2 (selinux) [установлен]
    usr/bin/apol
```

**Comment by freedom1b2830** [comment]
#apol 

```
Traceback (most recent call last):
  File "/usr/bin/apol", line 11, in <module>
    from PyQt5.QtWidgets import QApplication
ModuleNotFoundError: No module named 'PyQt5'
```
